# ----------------------------------------------------------
# Packages
# ----------------------------------------------------------

packages=(
    "wget"
    "unzip"
    "git"
    "gum"    
    "hyprland"
    "hyprland-devel"
    "hyprland-qtutils"
    "waybar"
    "rofi-wayland"
    "kitty"
    "dunst"
    "thunar"
    "xdg-desktop-portal-hyprland"
    "libqt5-qtwayland"
    "qt6-wayland"
    "hyprpaper"
    "hyprlock"
    "firefox"
    "fontawesome-fonts"
    "vim"
    "fastfetch"
    "mozilla-fira-fonts" 
    "fira-code-fonts" 
    "jq"
    "brightnessctl"
    "NetworkManager-connection-editor"
    "wireplumber"
    "wlogout"
    "flatpak"
)